-- ============================================================
-- V502: Upgrade all EMAIL templates to styled HTML and add new templates
-- ============================================================

-- Helper: Reusable HTML wrapper for all emails
-- Each UPDATE below wraps the content in a branded ForexBridge email layout.

-- ── Transaction Status Updates ──

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#1B3571;margin:0 0 16px;font-size:20px;">Transfer Created</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your transfer <strong>{{referenceNumber}}</strong> has been created.</p><table style="width:100%;background:#f8f9fb;border-radius:8px;padding:16px;margin:16px 0;" cellpadding="8"><tr><td style="color:#718096;font-size:13px;">You Send</td><td style="text-align:right;font-weight:600;color:#1B3571;">{{sendAmount}} {{sendCurrency}}</td></tr><tr><td style="color:#718096;font-size:13px;">Recipient Gets</td><td style="text-align:right;font-weight:600;color:#059669;">{{receiveAmount}} {{receiveCurrency}}</td></tr><tr><td style="color:#718096;font-size:13px;">Recipient</td><td style="text-align:right;font-weight:500;">{{beneficiaryName}}</td></tr><tr><td style="color:#718096;font-size:13px;">Rate</td><td style="text-align:right;font-family:monospace;">{{exchangeRate}}</td></tr><tr><td style="color:#718096;font-size:13px;">Fee</td><td style="text-align:right;">{{feeAmount}} {{feeCurrency}}</td></tr></table><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'TX_CREATED' AND channel = 'EMAIL' AND language = 'en';

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#1B3571;margin:0 0 16px;font-size:20px;">Transfer Completed!</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Great news! Your transfer <strong>{{referenceNumber}}</strong> has been successfully delivered.</p><div style="background:#ecfdf5;border-radius:8px;padding:16px;text-align:center;margin:16px 0;"><p style="color:#059669;font-size:22px;font-weight:700;margin:0;">{{receiveAmount}} {{receiveCurrency}}</p><p style="color:#065f46;font-size:13px;margin:4px 0 0;">delivered to {{beneficiaryName}}</p></div><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'TX_PAID' AND channel = 'EMAIL' AND language = 'en';

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#dc2626;margin:0 0 16px;font-size:20px;">Transfer Failed</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Unfortunately, your transfer <strong>{{referenceNumber}}</strong> could not be completed.</p><div style="background:#fef2f2;border-left:4px solid #dc2626;border-radius:4px;padding:12px 16px;margin:16px 0;"><p style="color:#991b1b;font-size:14px;margin:0;"><strong>Reason:</strong> {{reason}}</p></div><p style="color:#4a5568;font-size:15px;line-height:1.6;">Please contact our support team for assistance.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'TX_FAILED' AND channel = 'EMAIL' AND language = 'en';

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#1B3571;margin:0 0 16px;font-size:20px;">Transfer Processing</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your payment for transfer <strong>{{referenceNumber}}</strong> has been received and is now being processed.</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">We will notify you when the funds are delivered to your recipient.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'TX_PROCESSING' AND channel = 'EMAIL' AND language = 'en';

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#1B3571;margin:0 0 16px;font-size:20px;">Transfer Cancelled</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your transfer <strong>{{referenceNumber}}</strong> has been cancelled as requested.</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">If you did not request this cancellation, please contact us immediately.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'TX_CANCELLED' AND channel = 'EMAIL' AND language = 'en';

-- ── KYC Templates ──

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#059669;margin:0 0 16px;font-size:20px;">Document Approved</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your <strong>{{documentType}}</strong> has been verified and approved.</p><div style="background:#ecfdf5;border-radius:8px;padding:16px;text-align:center;margin:16px 0;"><p style="color:#059669;font-size:16px;font-weight:600;margin:0;">&#x2705; Verification Successful</p></div><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your account limits have been updated. You can now send higher amounts.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'KYC_DOCUMENT_APPROVED' AND channel = 'EMAIL' AND language = 'en';

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#dc2626;margin:0 0 16px;font-size:20px;">Document Rejected</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Unfortunately, your <strong>{{documentType}}</strong> could not be verified.</p><div style="background:#fef2f2;border-left:4px solid #dc2626;border-radius:4px;padding:12px 16px;margin:16px 0;"><p style="color:#991b1b;font-size:14px;margin:0;"><strong>Reason:</strong> {{rejectionReason}}</p></div><p style="color:#4a5568;font-size:15px;line-height:1.6;">Please upload a clear, valid document and try again.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'KYC_DOCUMENT_REJECTED' AND channel = 'EMAIL' AND language = 'en';

UPDATE notification_templates SET body_template =
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#059669;margin:0 0 16px;font-size:20px;">Account Upgraded!</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Congratulations! Your account has been upgraded.</p><div style="background:#ecfdf5;border-radius:8px;padding:20px;text-align:center;margin:16px 0;"><p style="color:#065f46;font-size:13px;margin:0 0 4px;">Your new tier</p><p style="color:#059669;font-size:24px;font-weight:700;margin:0;">{{newTier}}</p></div><p style="color:#4a5568;font-size:15px;line-height:1.6;">You now have access to higher transaction limits and additional features.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'
WHERE template_code = 'KYC_TIER_UPGRADED' AND channel = 'EMAIL' AND language = 'en';

-- ── NEW TEMPLATES ──

-- Document Expiry Reminder
INSERT INTO notification_templates (template_code, channel, language, subject, body_template) VALUES
('KYC_DOCUMENT_EXPIRING', 'EMAIL', 'en', 'Action Required: Document Expiring Soon',
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#d97706;margin:0 0 16px;font-size:20px;">Document Expiring Soon</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your <strong>{{documentType}}</strong> will expire on <strong>{{expiryDate}}</strong>.</p><div style="background:#fffbeb;border-left:4px solid #d97706;border-radius:4px;padding:12px 16px;margin:16px 0;"><p style="color:#92400e;font-size:14px;margin:0;">Please upload a new document before it expires to avoid service interruption.</p></div><p style="color:#4a5568;font-size:15px;line-height:1.6;">You can upload your new document from your profile page.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'),

-- Document Expired
('KYC_DOCUMENT_EXPIRED', 'EMAIL', 'en', 'Document Expired - Action Required',
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#dc2626;margin:0 0 16px;font-size:20px;">Document Expired</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your <strong>{{documentType}}</strong> has expired. Your account may be restricted until you upload a valid document.</p><div style="background:#fef2f2;border-left:4px solid #dc2626;border-radius:4px;padding:12px 16px;margin:16px 0;"><p style="color:#991b1b;font-size:14px;margin:0;">Please upload a new document immediately to continue using our services.</p></div><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'),

-- User Verified (full KYC complete)
('USER_VERIFIED', 'EMAIL', 'en', 'Account Fully Verified',
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#059669;margin:0 0 16px;font-size:20px;">You''re Fully Verified!</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your identity has been fully verified. You now have access to all ForexBridge features.</p><div style="background:#ecfdf5;border-radius:8px;padding:20px;text-align:center;margin:16px 0;"><p style="color:#059669;font-size:40px;margin:0 0 8px;">&#x2705;</p><p style="color:#065f46;font-size:16px;font-weight:600;margin:0;">Identity Verified</p></div><table style="width:100%;margin:16px 0;" cellpadding="6"><tr><td style="color:#718096;font-size:13px;">Transfer limit</td><td style="text-align:right;font-weight:600;color:#1B3571;">Unlocked</td></tr><tr><td style="color:#718096;font-size:13px;">All payment methods</td><td style="text-align:right;font-weight:600;color:#059669;">Available</td></tr></table><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'),

-- Account Blocked / Suspended
('ACCOUNT_SUSPENDED', 'EMAIL', 'en', 'Account Suspended',
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#dc2626;margin:0 0 16px;font-size:20px;">Account Suspended</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your ForexBridge account has been temporarily suspended.</p><div style="background:#fef2f2;border-left:4px solid #dc2626;border-radius:4px;padding:12px 16px;margin:16px 0;"><p style="color:#991b1b;font-size:14px;margin:0;"><strong>Reason:</strong> {{reason}}</p></div><p style="color:#4a5568;font-size:15px;line-height:1.6;">During this time, you will not be able to initiate new transfers. If you believe this is an error, please contact our support team.</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Email: <a href="mailto:support@forexbridge.com" style="color:#1B3571;">support@forexbridge.com</a></p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'),

-- Account Reactivated
('ACCOUNT_REACTIVATED', 'EMAIL', 'en', 'Account Reactivated',
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#059669;margin:0 0 16px;font-size:20px;">Account Reactivated</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your ForexBridge account has been reactivated. You can now use all services as normal.</p><div style="background:#ecfdf5;border-radius:8px;padding:16px;text-align:center;margin:16px 0;"><p style="color:#059669;font-size:16px;font-weight:600;margin:0;">&#x2705; Your account is active</p></div><p style="color:#4a5568;font-size:15px;line-height:1.6;">Thank you for your patience.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>'),

-- Transaction Status Updated (generic)
('TX_STATUS_UPDATED', 'EMAIL', 'en', 'Transfer Update - {{referenceNumber}}',
'<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:''Segoe UI'',sans-serif;background:#f4f6f9;"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;margin:0 auto;padding:40px 20px;"><tr><td style="background:#1B3571;padding:24px;text-align:center;border-radius:12px 12px 0 0;"><h1 style="color:#fff;margin:0;font-size:24px;">ForexBridge</h1></td></tr><tr><td style="background:#fff;padding:32px 24px;border-radius:0 0 12px 12px;box-shadow:0 2px 8px rgba(0,0,0,0.06);"><h2 style="color:#1B3571;margin:0 0 16px;font-size:20px;">Transfer Status Updated</h2><p style="color:#4a5568;font-size:15px;line-height:1.6;">Hi {{firstName}},</p><p style="color:#4a5568;font-size:15px;line-height:1.6;">Your transfer <strong>{{referenceNumber}}</strong> has been updated.</p><table style="width:100%;background:#f8f9fb;border-radius:8px;padding:16px;margin:16px 0;" cellpadding="8"><tr><td style="color:#718096;font-size:13px;">Previous Status</td><td style="text-align:right;font-weight:500;">{{previousStatus}}</td></tr><tr><td style="color:#718096;font-size:13px;">New Status</td><td style="text-align:right;font-weight:600;color:#1B3571;">{{newStatus}}</td></tr><tr><td style="color:#718096;font-size:13px;">Amount</td><td style="text-align:right;font-family:monospace;">{{sendAmount}} {{sendCurrency}}</td></tr><tr><td style="color:#718096;font-size:13px;">Recipient</td><td style="text-align:right;">{{beneficiaryName}}</td></tr></table><p style="color:#4a5568;font-size:15px;line-height:1.6;">Log in to your account for full details.</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0;"><p style="color:#a0aec0;font-size:12px;text-align:center;">ForexBridge — Secure International Money Transfers</p></td></tr></table></body></html>');

-- In-app templates for the new types
INSERT INTO notification_templates (template_code, channel, language, subject, body_template) VALUES
('KYC_DOCUMENT_EXPIRING', 'IN_APP', 'en', 'Document Expiring', 'Your {{documentType}} expires on {{expiryDate}}. Please upload a new one.'),
('KYC_DOCUMENT_EXPIRED', 'IN_APP', 'en', 'Document Expired', 'Your {{documentType}} has expired. Please upload a new document.'),
('USER_VERIFIED', 'IN_APP', 'en', 'Fully Verified', 'Your identity has been fully verified. All features unlocked!'),
('ACCOUNT_SUSPENDED', 'IN_APP', 'en', 'Account Suspended', 'Your account has been suspended. Reason: {{reason}}'),
('ACCOUNT_REACTIVATED', 'IN_APP', 'en', 'Account Reactivated', 'Your account has been reactivated. Welcome back!'),
('TX_STATUS_UPDATED', 'IN_APP', 'en', 'Transfer Updated', 'Transfer {{referenceNumber}}: status changed to {{newStatus}}.');
