CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id BIGINT NOT NULL PRIMARY KEY,
    rate_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    promotional BOOLEAN NOT NULL DEFAULT TRUE,
    transaction_updates BOOLEAN NOT NULL DEFAULT TRUE,
    security_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    kyc_updates BOOLEAN NOT NULL DEFAULT TRUE,
    compliance_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    system_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    email_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
