CREATE TABLE IF NOT EXISTS remit_one_transactions (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    transaction_id      VARCHAR(100) NOT NULL,
    payment_status      VARCHAR(50),
    message             TEXT,
    trans_session_id    VARCHAR(100),
    trans_type          VARCHAR(50),
    remitter_id         VARCHAR(100),
    remitter_name       VARCHAR(255),
    beneficiary_id      VARCHAR(100),
    beneficiary_name    VARCHAR(255),
    destination_country VARCHAR(10),
    source_currency     VARCHAR(10),
    destination_currency VARCHAR(10),
    source_amount       DECIMAL(18,4),
    rate                DECIMAL(18,8),
    destination_amount  DECIMAL(18,4),
    commission          DECIMAL(18,4),
    tax                 DECIMAL(18,4),
    remitter_pay_amount DECIMAL(18,4),
    comments_to_beneficiary TEXT,
    raw_response        LONGTEXT,
    created_on          DATETIME,
    INDEX idx_rot_txn_id (transaction_id)
);
