-- Generated by transliterate-names.js. Review the matching review.tsv before applying.
-- Each UPDATE is guarded by the original value, so it is a no-op if the row changed since export.
START TRANSACTION;
UPDATE `beneficiaries` SET `full_name` = 'Mutasim Ahmed Habib Jaber' WHERE `id` = 101 AND `full_name` = 'معتصم احمد حبيب جابر';
UPDATE `beneficiaries` SET `full_name` = 'Omar Mohamed Ahmed Mohamed Din' WHERE `id` = 102 AND `full_name` = 'عمر محمد احمد محمد دين';
UPDATE `beneficiaries` SET `full_name` = 'Muaz Abdelqader Hussein Abdelqader' WHERE `id` = 104 AND `full_name` = 'معاذ عبدالقادر حسين عبدالقادر';
-- Rows to update: 3. Atomic: all succeed or none (COMMIT at end).
COMMIT;
