#!/usr/bin/env node
/*
 * transliterate-names.js — one-off helper to convert Arabic names already stored
 * in the DB to a Latin spelling, using the SAME logic as the app's appLatinName
 * directive (src/app/shared/utils/transliterate.ts).
 *
 * It does NOT touch the database. It reads a TSV you exported from MySQL and
 * emits (a) a human-readable review file and (b) a SQL file of guarded per-row
 * UPDATEs wrapped in a single transaction. You review, back up, then apply.
 *
 * Input TSV (tab-separated, no header):   <id>\t<currentValue>
 * Usage:
 *   node transliterate-names.js <table> <idCol> <valueCol> <input.tsv> <out.sql> <review.tsv>
 */

const fs = require('fs');

// ---- transliteration (mirror of transliterate.ts) -------------------------
const WORDS = {
  'محمد':'Mohamed','احمد':'Ahmed','أحمد':'Ahmed','محمود':'Mahmoud',
  'حسن':'Hassan','حسين':'Hussein','علي':'Ali','عمر':'Omar',
  'عثمان':'Othman','ابراهيم':'Ibrahim','إبراهيم':'Ibrahim','اسماعيل':'Ismail',
  'يوسف':'Yousif','ادريس':'Idris','إدريس':'Idris','خالد':'Khalid',
  'صلاح':'Salah','مصطفى':'Mustafa','طارق':'Tariq','معتصم':'Mutasim',
  'معاذ':'Muaz','حمزة':'Hamza','بشير':'Bashir','نصر':'Nasr',
  'سليمان':'Suliman','الطيب':'Eltayeb','الصادق':'Elsadig','الامين':'Elamin',
  'الأمين':'Elamin','بكري':'Bakri','آدم':'Adam','ادم':'Adam',
  'جابر':'Jaber','حبيب':'Habib','دين':'Din','نور':'Noor',
  'الفاتح':'Elfatih','الهادي':'Elhadi','عبدالله':'Abdullah',
  'عبدالرحمن':'Abdelrahman','عبدالقادر':'Abdelqader','عبدالعزيز':'Abdelaziz',
  'عبدالرحيم':'Abdelrahim','عبدالرؤوف':'Abderrauf',
  'فاطمة':'Fatima','عائشة':'Aisha','مريم':'Mariam','زينب':'Zainab',
  'سارة':'Sara','ساره':'Sara','هبة':'Hiba','اسراء':'Israa',
  'صديق':'Siddig','الصديق':'Elsiddig','موسى':'Musa','عيسى':'Issa',
  'يعقوب':'Yagoub','سعد':'Saad','سعيد':'Saeed','ربيع':'Rabie',
  'الطاهر':'Eltahir','النور':'Elnour','بابكر':'Babiker','كمال':'Kamal'
};
const LETTERS = {
  'ا':'a','أ':'a','إ':'i','آ':'a','ٱ':'a','ٲ':'a','ٳ':'i',
  'ب':'b','ت':'t','ث':'th','ج':'j','ح':'h','خ':'kh',
  'د':'d','ذ':'dh','ر':'r','ز':'z','س':'s','ش':'sh',
  'ص':'s','ض':'d','ط':'t','ظ':'z','ع':'a','غ':'gh',
  'ف':'f','ق':'q','ك':'k','گ':'g','ل':'l','م':'m','ن':'n',
  'ه':'h','ة':'a','و':'w','ؤ':'w','ي':'y','ى':'a','ئ':'y',
  'ء':'','پ':'p','چ':'ch','ژ':'zh','ڤ':'v'
};
const DIGITS = {
  '٠':'0','١':'1','٢':'2','٣':'3','٤':'4','٥':'5','٦':'6','٧':'7','٨':'8','٩':'9',
  '۰':'0','۱':'1','۲':'2','۳':'3','۴':'4','۵':'5','۶':'6','۷':'7','۸':'8','۹':'9'
};
const DIACRITICS = new RegExp('[\\u0610-\\u061A\\u064B-\\u065F\\u0670\\u06D6-\\u06ED\\u0640]', 'g');
const ARABIC = new RegExp('[\\u0600-\\u06FF\\u0750-\\u077F]');

function hasArabic(s){ return !!s && ARABIC.test(s); }
function letterMap(token){
  let out = '';
  for (const ch of token) {
    if (LETTERS[ch] !== undefined) out += LETTERS[ch];
    else if (DIGITS[ch] !== undefined) out += DIGITS[ch];
    else out += ch;
  }
  return out;
}
function capitalize(s){ return s ? s.charAt(0).toUpperCase() + s.slice(1) : s; }
function transliterateToken(token){
  if (!hasArabic(token)) return token;
  if (WORDS[token]) return WORDS[token];
  if (token.startsWith('عبدال') && token.length > 5) return 'Abdel' + letterMap(token.slice(5));
  return capitalize(letterMap(token));
}
function arabicToLatin(input){
  if (!input || !hasArabic(input)) return input;
  const stripped = input.replace(DIACRITICS, '');
  const tokens = stripped.split(/(\s+)/);
  return tokens.map(t => (/^\s+$/.test(t) ? ' ' : transliterateToken(t))).join('').replace(/\s+/g, ' ').trim();
}

// ---- SQL escaping (MySQL: backslash + quote) ------------------------------
function esc(s){ return String(s).replace(/\\/g, '\\\\').replace(/'/g, "''"); }

// ---- main -----------------------------------------------------------------
const [,, table, idCol, valueCol, inFile, outSql, reviewFile] = process.argv;
if (!table || !idCol || !valueCol || !inFile || !outSql || !reviewFile) {
  console.error('Usage: node transliterate-names.js <table> <idCol> <valueCol> <input.tsv> <out.sql> <review.tsv>');
  process.exit(1);
}

const lines = fs.readFileSync(inFile, 'utf8').split('\n').filter(l => l.length);
const sql = [];
const review = [];
let changed = 0, skipped = 0;

sql.push('-- Generated by transliterate-names.js. Review the matching review.tsv before applying.');
sql.push('-- Each UPDATE is guarded by the original value, so it is a no-op if the row changed since export.');
sql.push('START TRANSACTION;');

for (const line of lines) {
  const tab = line.indexOf('\t');
  if (tab < 0) continue;
  const id = line.slice(0, tab);
  const value = line.slice(tab + 1);
  if (!hasArabic(value)) { skipped++; continue; }
  const converted = arabicToLatin(value);
  if (!converted || converted === value || hasArabic(converted)) { skipped++; continue; }
  changed++;
  review.push(`${id}\t${value}\t${converted}`);
  sql.push(
    `UPDATE \`${table}\` SET \`${valueCol}\` = '${esc(converted)}' ` +
    `WHERE \`${idCol}\` = ${/^\d+$/.test(id) ? id : `'${esc(id)}'`} ` +
    `AND \`${valueCol}\` = '${esc(value)}';`
  );
}

sql.push(`-- Rows to update: ${changed}. Atomic: all succeed or none (COMMIT at end).`);
sql.push('COMMIT;');

fs.writeFileSync(outSql, sql.join('\n') + '\n', 'utf8');
fs.writeFileSync(reviewFile, 'id\toriginal\tconverted\n' + review.join('\n') + '\n', 'utf8');
console.log(`${table}.${valueCol}: ${changed} to update, ${skipped} skipped → ${outSql}, ${reviewFile}`);
