CREATE TABLE IF NOT EXISTS amal_transactions (
    id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    transaction_type        ENUM('BANK','MOBILE','CASH') NOT NULL,
    sender_country          VARCHAR(10)  NOT NULL DEFAULT 'GB',
    destination_country     VARCHAR(10)  NOT NULL,
    amount                  DECIMAL(15,2) NOT NULL,
    currency                VARCHAR(10)  NOT NULL,
    beneficiary_name        VARCHAR(255) NOT NULL,
    beneficiary_account     VARCHAR(100),
    mobile_number           VARCHAR(50),
    bank_code               VARCHAR(50),
    service_operator        VARCHAR(100),
    amal_transaction_id     VARCHAR(100),
    reference_number        VARCHAR(100),
    status                  ENUM('PENDING','INITIATED','PROCESSING','SUCCESS','FAILED') NOT NULL DEFAULT 'PENDING',
    raw_request             JSON,
    raw_response            JSON,
    created_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_amal_user     (user_id),
    INDEX idx_amal_status   (status),
    INDEX idx_amal_ref      (reference_number)
);
