-- Missing beneficiaries (12 under vinay user 1356) + OMAR user + his beneficiary.
-- Self-contained; safe to run once on live. Guarded so re-runs don't duplicate.
SET SESSION sql_mode='';
-- 1) OMAR user (no legacy email -> placeholder). Only if not already present.
INSERT INTO users (uuid,email,phone,password_hash,first_name,last_name,status,email_verified,user_type,kyc_tier,payin_enabled,created_at,updated_at)
SELECT UUID(),'omar.basheri.19471@migrated.remitm.com','07877999371','OMAR9371','OMAR ABDULATI','BASHERI','ACTIVE',0,'INDIVIDUAL','TIER_0',0,'2025-08-09 17:39:29',NOW()
FROM dual WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='omar.basheri.19471@migrated.remitm.com');
SET @omar_id = (SELECT id FROM users WHERE email='omar.basheri.19471@migrated.remitm.com' LIMIT 1);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT @omar_id,'OMAR ABDULATI  BASHERI',NULL,'KHARTOUM SUDAN','SD','BANK_DEPOSIT',NULL,'Khartoum Bank','1266898',NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=@omar_id AND b.full_name<=>'OMAR ABDULATI  BASHERI' AND b.account_number<=>'1266898');
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'Sangu kolle',NULL,'Karnataka','SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'Sangu kolle' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'',NULL,NULL,'SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'Sonu kumar',NULL,'Gujurat','SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'Sonu kumar' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'',NULL,NULL,'SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'gff gfgd',NULL,'gse','SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'gff gfgd' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'fgfd gfdg',NULL,'vcg','SD','BANK_DEPOSIT',NULL,'Alsalam Bank','98765234',NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'fgfd gfdg' AND b.account_number<=>'98765234');
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'Vinay Thumma',NULL,'Dhsj','SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'Vinay Thumma' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'Vinay Thumma',NULL,'Shw','SD','BANK_DEPOSIT',NULL,'El -Nilien Bank','987654321',NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'Vinay Thumma' AND b.account_number<=>'987654321');
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'Teena kumari',NULL,'Karnataka','SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'Teena kumari' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'vinay htt',NULL,'uytf','GB','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'vinay htt' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'gfhj hgj',NULL,'gfhj','SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'gfhj hgj' AND b.account_number<=>NULL);
INSERT INTO beneficiaries (user_id,full_name,email,address,country,delivery_method,mobile_number,bank_name,account_number,swift_bic,iban,branch_state,branch_city,is_blocked,is_favourite,created_at,updated_at) SELECT 1356,'frghfg fgfh',NULL,'dsfgh','SD','CASH_PICKUP',NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,NOW(),NOW() FROM dual WHERE NOT EXISTS (SELECT 1 FROM beneficiaries b WHERE b.user_id=1356 AND b.full_name<=>'frghfg fgfh' AND b.account_number<=>NULL);
